### PR TITLE
(update) The two first if statements in defaultToWhiteSpace() are unreac...

### PR DESCRIPTION
**Pull request by yagoferrer**
...hable because the variable 'from' is hard-coded value. The regex it's just wrapping the text with '['+ text + ']'. This function looks like an old code. Did I make ng-tasty faster?? :D

### CODE REVIEW

**Comment by Zizzamia** [comment]
Can you please sync with the latest master, will be easier merge.

**Comment by yagoferrer** [comment]
Sure done bro!

**Comment by Zizzamia** [comment]
Grazie, this PR was really tasty! I will in the next release start doing benchmark also for all the `filter`.

**Comment by yagoferrer** [comment]
bella zio!

**Comment by Zizzamia** [comment]
😄

**Comment by yagoferrer** [comment]
Code coverage +0.09%!

**Pull request merged**
